In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

In [6]:
# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

abs:
 [[1 2]
 [3 4]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]]

floor:
 [[1. 2.]
 [3. 4.]]

ceil:
 [[1. 2.]
 [3. 4.]]


In [9]:
import numpy as np

# Creating a 3x2 matrix with custom values
matrix_3x2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Trigonometric functions
sin_values = np.sin(matrix_3x2)
cos_values = np.cos(matrix_3x2)
tan_values = np.tan(matrix_3x2)

# For inverse trig functions, scale values to [-1, 1]
scaled_matrix = np.clip(matrix_3x2 / np.max(matrix_3x2), -1, 1)
asin_values = np.arcsin(scaled_matrix)
acos_values = np.arccos(scaled_matrix)
atan_values = np.arctan(matrix_3x2)

# Exponential and logarithmic functions
exp_values = np.exp(matrix_3x2)
log_values = np.log(matrix_3x2)  # natural log

# Absolute value and square root
abs_values = np.abs(matrix_3x2)
sqrt_values = np.sqrt(matrix_3x2)

# Remainder when divided by 2
rem_values = np.remainder(matrix_3x2, 2)

# Rounding functions
round_values = np.round(matrix_3x2)
floor_values = np.floor(matrix_3x2)
ceil_values = np.ceil(matrix_3x2)

# Display results
print("3x2 Matrix:\n", matrix_3x2)

print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)

print("\nasin:\n", asin_values)
print("\nacos:\n", acos_values)
print("\natan:\n", atan_values)

print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)

print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)

print("\nremainder (mod 2):\n", rem_values)

print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]

asin:
 [[0.16744808 0.33983691]
 [0.52359878 0.72972766]
 [0.98511078 1.57079633]]

acos:
 [[1.40334825 1.23095942]
 [1.04719755 0.84106867]
 [0.58568554 0.        ]]

atan:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[1 2]
 [3 4]
 [5 6]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

remainder (mod 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]
 [5 6]]

floor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

ceil:
 [[1. 2.]
 [3. 4.]
 [5. 6.]

In [10]:
import numpy as np

# Create a 2x3 matrix with float values
matrix = np.array([
    [2.1, 4.7, 1.3],
    [5.9, 0.8, 3.6]
])

print("Matrix:\n", matrix)

max_value = np.max(matrix)
min_value = np.min(matrix)

max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_index = np.unravel_index(np.argmin(matrix), matrix.shape)

print("\nMax value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)


vector_length = np.linalg.norm(matrix)
print("\nVector length (Euclidean norm):", vector_length)


rowwise_sorted_desc = np.sort(matrix, axis=1)[:, ::-1]

# Entire matrix descending
entire_sorted_desc = np.sort(matrix.flatten())[::-1]

print("\nRow-wise sorted (descending):\n", rowwise_sorted_desc)
print("\nEntire matrix sorted (descending):\n", entire_sorted_desc)


sum_values = np.sum(matrix)
product_values = np.prod(matrix)

print("\nSum of all elements:", sum_values)
print("Product of all elements:", product_values)


median_value = np.median(matrix)
mean_value = np.mean(matrix)
std_value = np.std(matrix)

print("\nMedian:", median_value)
print("Mean:", mean_value)
print("Standard Deviation:", std_value)


Matrix:
 [[2.1 4.7 1.3]
 [5.9 0.8 3.6]]

Max value: 5.9 at index (np.int64(1), np.int64(0))
Min value: 0.8 at index (np.int64(1), np.int64(1))

Vector length (Euclidean norm): 8.752142594816426

Row-wise sorted (descending):
 [[4.7 2.1 1.3]
 [5.9 3.6 0.8]]

Entire matrix sorted (descending):
 [5.9 4.7 3.6 2.1 1.3 0.8]

Sum of all elements: 18.400000000000002
Product of all elements: 218.02435200000005

Median: 2.85
Mean: 3.066666666666667
Standard Deviation: 1.8336363385966754
