In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import numpy as np

# Student ID based values , so my id is 30
d1 = 0
d2 = 3

A = np.array([
    [d1 + 2, d2 + 1],
    [2*d1,   d2 + 2]
])

print("Matrix A:")
print(A)


Matrix A:
[[2 4]
 [0 5]]


In [5]:
2#Analyze Matrix A

# Shape
print("\nShape of A:", A.shape)

# Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Rank
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

# Eigenvalues
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues_A)

# Inverse
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is singular, inverse does not exist.")



Shape of A: (2, 2)
Determinant of A: 9.999999999999998
Rank of A: 2
Eigenvalues of A: [2. 5.]
Inverse of A:
 [[ 0.5 -0.4]
 [ 0.   0.2]]


In [7]:
#3: Value Change Experiment

B = A.copy()
B[0, 0] = B[0, 0] + 1   # Changed element (0,0)

print("\nMatrix B (after changing A[0][0] by +1):")
print(B)



Matrix B (after changing A[0][0] by +1):
[[3 4]
 [0 5]]


In [8]:
#4: Re-analyze Matrix B
# Shape
print("\nShape of B:", B.shape)

# Determinant
det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

# Rank
rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

# Eigenvalues
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print("Eigenvalues of B:", eigenvalues_B)

# Inverse
if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is singular, inverse does not exist.")



Shape of B: (2, 2)
Determinant of B: 15.0
Rank of B: 2
Eigenvalues of B: [3. 5.]
Inverse of B:
 [[ 0.33333333 -0.26666667]
 [ 0.          0.2       ]]
